openapi: 3.1.0
info:
  title: Open Payments - Shared schemas
  version: '1.0'
  license:
    name: Apache 2.0
    identifier: Apache-2.0
  summary: Open Payments - Shared schemas
  description: 'Shared schemas used across Open Payments APIs'
  contact:
    email: tech@interledger.org
components:
  schemas:
    amount:
      title: amount
      type: object
      properties:
        value:
          type: string
          format: uint64
          description: 'The value is an unsigned 64-bit integer amount, represented as a string.'
        assetCode:
          $ref: '#/components/schemas/assetCode'
        assetScale:
          $ref: '#/components/schemas/assetScale'
      required:
        - value
        - assetCode
        - assetScale
    assetCode:
      title: Asset code
      type: string
      description: The assetCode is a code that indicates the underlying asset. An ISO4217 currency code should be used whenever possible. The ISO4217 representation of the US Dollar is USD.
    assetScale:
      title: Asset scale
      type: integer
      minimum: 0
      maximum: 255
      description: The number of decimal places used to represent the minimum value of the asset. As an example, USD has an asset scale of 2 with a minimum value of $0.01. An integer amount of 1000 with an `assetCode` of USD and `assetScale` of 2 translates to $10.00
    receiver:
      title: Receiver
      type: string
      description: The URL of the incoming payment that is being paid.
      format: uri
      pattern: '^(https|http)://(.+)/incoming-payments/(.+)$'
      examples:
        - 'https://ilp.interledger-test.dev/incoming-payments/08394f02-7b7b-45e2-b645-51d04e7c330c'
        - 'http://ilp.interledger-test.dev/incoming-payments/08394f02-7b7b-45e2-b645-51d04e7c330c'
        - 'https://ilp.interledger-test.dev/incoming-payments/1'
    walletAddress:
      title: Wallet Address
      type: string
      description: 'URL of a wallet address hosted by a Rafiki instance.'
      format: uri
