version: '3.8'

services:
  swagger-ui:
    image: docker.swagger.io/swaggerapi/swagger-ui
    container_name: swagger-ui
    ports:
      - "8000:8080"
    volumes:
      - ../openapi:/tmp
    environment:
      - SWAGGER_JSON=/tmp/resource-server.yaml
    restart: unless-stopped